#!/usr/bin/env tsx
/**
 * Generates TypeScript types for VS Code workbench color keys.
 * Fetches color definitions from VS Code's source and extracts all registerColor keys.
 *
 * Run: npx tsx tools/generateVSCodeColorTypes.ts
 */

const COLOR_FILES = [
  // Core platform colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/baseColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/chartsColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/editorColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/inputColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/listColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/menuColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/minimapColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/miscColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/quickpickColors.ts',
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/platform/theme/common/colors/searchColors.ts',
  // Workbench theme colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/common/theme.ts',
  // Editor colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/editor/common/core/editorColorRegistry.ts',
  // Debug colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/debug/browser/debugColors.ts',
  // Terminal colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts',
  // Notebook colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts',
  // SCM/Git colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/scm/browser/scmColors.ts',
  // Extensions colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/extensions/browser/extensionsColors.ts',
  // Peek view colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/editor/contrib/peekView/browser/peekView.ts',
  // Diff editor colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/editor/browser/widget/diffEditor/colors.ts',
  // Merge editor colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/mergeEditor/browser/mergeEditorColors.ts',
  // Testing colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/testing/browser/theme.ts',
  // Inline chat colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/inlineChat/common/inlineChat.ts',
  // Comments colors
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/contrib/comments/browser/commentsColors.ts',
];

async function fetchColorFile(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    console.warn(`Failed to fetch ${url}: ${response.status}`);
    return '';
  }
  return response.text();
}

function extractColorKeys(source: string): string[] {
  const keys: string[] = [];

  // Match registerColor('key.name', ...) patterns
  const registerColorRegex = /registerColor\(\s*['"]([^'"]+)['"]/g;
  let match;

  while ((match = registerColorRegex.exec(source)) !== null) {
    keys.push(match[1]);
  }

  return keys;
}

async function main() {
  console.log('Fetching VS Code color definitions...\n');

  const allKeys = new Set<string>();

  for (const url of COLOR_FILES) {
    const filename = url.split('/').pop();
    console.log(`Fetching ${filename}...`);

    const source = await fetchColorFile(url);
    const keys = extractColorKeys(source);

    keys.forEach((key) => allKeys.add(key));
    console.log(`  Found ${keys.length} colors`);
  }

  const sortedKeys = Array.from(allKeys).sort();

  console.log(`\nTotal unique color keys: ${sortedKeys.length}\n`);

  // Generate TypeScript type
  const output = `// ==========================================================================
// Auto-generated by tools/generateVSCodeColorTypes.ts - DO NOT EDIT MANUALLY
// Run: npx tsx tools/generateVSCodeColorTypes.ts
// Generated from VS Code source: https://github.com/microsoft/vscode
// ==========================================================================

/**
 * All valid VS Code workbench color keys.
 * Use this type for type-safe theme color definitions.
 */
export type VSCodeColorKey =
${sortedKeys.map((key) => `  | "${key}"`).join('\n')};

/**
 * A record type for VS Code theme colors.
 * Keys are VS Code color keys, values are hex color strings.
 */
export type VSCodeColors = Partial<Record<VSCodeColorKey, string>>;

/**
 * Array of all valid color keys (useful for validation).
 */
export const vscodeColorKeys = [
${sortedKeys.map((key) => `  "${key}",`).join('\n')}
] as const;
`;

  const outputPath = new URL('../generated/vscodeColorTypes.ts', import.meta.url);
  const fs = await import('fs/promises');
  await fs.writeFile(outputPath, output);

  console.log(`✓ Generated src/vscodeColorTypes.ts with ${sortedKeys.length} color keys`);
}

main().catch(console.error);
