#!/usr/bin/env tsx
/**
 * Generates TypeScript types for TextMate scopes.
 * Fetches standard scopes from VS Code + extracts scopes from current theme.
 *
 * Run: npx tsx tools/generateTextMateScopeTypes.ts
 */

import { readFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const VSCODE_SCHEMA_URL =
  'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/workbench/services/themes/common/colorThemeSchema.ts';

async function fetchVSCodeScopes(): Promise<string[]> {
  console.log('Fetching VS Code standard scopes...');

  const response = await fetch(VSCODE_SCHEMA_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch: ${response.status}`);
  }

  const source = await response.text();

  // Extract the textMateScopes array
  const match = source.match(/const textMateScopes = \[([\s\S]*?)\];/);
  if (!match) {
    throw new Error('Could not find textMateScopes in source');
  }

  const scopesStr = match[1];
  const scopes: string[] = [];

  // Extract quoted strings
  const quoteRegex = /'([^']+)'/g;
  let scopeMatch;
  while ((scopeMatch = quoteRegex.exec(scopesStr)) !== null) {
    scopes.push(scopeMatch[1]);
  }

  console.log(`  Found ${scopes.length} standard scopes`);
  return scopes;
}

async function extractThemeScopes(): Promise<string[]> {
  console.log('Extracting scopes from generated themes...');

  // Read all theme JSON files from the themes directory
  const themesDir = join(__dirname, '../../../themes');
  let themeFiles: string[] = [];

  try {
    const { readdir } = await import('fs/promises');
    const files = await readdir(themesDir);
    themeFiles = files.filter((f) => f.endsWith('.json'));
  } catch {
    console.log('  No theme files found in themes directory');
    return [];
  }

  if (themeFiles.length === 0) {
    console.log('  No theme files found. Run build:themes first.');
    return [];
  }

  const scopes = new Set<string>();

  // Extract scopes from all theme files
  for (const themeFile of themeFiles) {
    const themePath = join(themesDir, themeFile);
    const themeContent = await readFile(themePath, 'utf-8');
    const theme = JSON.parse(themeContent);

    if (theme.tokenColors && Array.isArray(theme.tokenColors)) {
      for (const rule of theme.tokenColors) {
        if (rule.scope) {
          if (typeof rule.scope === 'string') {
            scopes.add(rule.scope);
          } else if (Array.isArray(rule.scope)) {
            rule.scope.forEach((s: string) => scopes.add(s));
          }
        }
      }
    }
  }

  console.log(`  Found ${scopes.size} scopes across all themes`);
  return Array.from(scopes);
}

async function main() {
  const [vscodeScopes, themeScopes] = await Promise.all([
    fetchVSCodeScopes(),
    extractThemeScopes(),
  ]);

  // Combine and deduplicate
  const allScopes = new Set([...vscodeScopes, ...themeScopes]);
  const sortedScopes = Array.from(allScopes).sort();

  console.log(`\nTotal unique scopes: ${sortedScopes.length}`);

  // Categorize scopes by their root
  const categories = new Map<string, string[]>();
  for (const scope of sortedScopes) {
    const root = scope.split('.')[0];
    if (!categories.has(root)) {
      categories.set(root, []);
    }
    categories.get(root)!.push(scope);
  }

  // Generate TypeScript
  const output = `// ==========================================================================
// Auto-generated by tools/generateTextMateScopeTypes.ts - DO NOT EDIT MANUALLY
// Run: npx tsx tools/generateTextMateScopeTypes.ts
// ==========================================================================

/**
 * Standard TextMate scope selectors from VS Code.
 * These are the commonly used scope names for syntax highlighting.
 *
 * Note: TextMate scopes are hierarchical (e.g., "comment.block.documentation")
 * and themes can use partial matches. This type includes known scopes but
 * is not exhaustive - language grammars can define additional scopes.
 */
export type TextMateScope =
${sortedScopes.map((s) => `  | "${s}"`).join('\n')};

/**
 * Root scope categories (first segment of scope name).
 */
export type TextMateScopeRoot =
${Array.from(categories.keys())
  .sort()
  .map((r) => `  | "${r}"`)
  .join('\n')};

/**
 * Token color rule settings.
 */
export interface TokenColorSettings {
  foreground?: string;
  background?: string;
  fontStyle?: "italic" | "bold" | "underline" | "strikethrough" | (string & {});
}

/**
 * A token color rule for syntax highlighting.
 */
export interface TokenColorRule {
  name?: string;
  scope: TextMateScope | TextMateScope[] | (string & {}) | string[];
  settings: TokenColorSettings;
}

/**
 * Array of all known scope strings (useful for validation/autocomplete).
 */
export const textMateScopes = [
${sortedScopes.map((s) => `  "${s}",`).join('\n')}
] as const;

/**
 * Scopes organized by category for reference.
 */
export const textMateScopesByCategory = {
${Array.from(categories.entries())
  .sort(([a], [b]) => a.localeCompare(b))
  .map(
    ([cat, scopes]) =>
      `  "${cat}": [\n${scopes.map((s) => `    "${s}",`).join('\n')}\n  ] as const,`
  )
  .join('\n')}
} as const;
`;

  const fs = await import('fs/promises');
  const outputPath = join(__dirname, '../generated/textMateScopeTypes.ts');
  await fs.writeFile(outputPath, output);

  console.log(`\n✓ Generated src/textMateScopeTypes.ts`);
  console.log(`  - ${sortedScopes.length} scopes`);
  console.log(
    `  - ${categories.size} categories: ${Array.from(categories.keys()).sort().join(', ')}`
  );
}

main().catch(console.error);
